imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@StudySauceBundle/Resources/config/assets.php" }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        hinclude_default_template: "StudySauceBundle:Shared:hinclude.html.php"
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
#    fragments: { path: /_fragment }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    #read_from:      "%kernel.root_dir%/../web"
    write_to:       "%kernel.root_dir%/../web"
    use_controller: false
    bundles:        [ "StudySauceBundle", "Course1Bundle" ]
    #output: "/Symfony/web/app_dev.php/*"
    #java: /usr/bin/java
    #variables:
    #        env:      [dev, prod]
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    sinclude:
        class: StudySauce\Bundle\DependencyInjection\SIncludeFragmentRenderer
        arguments: ["@service_container", "@uri_signer", "", "@http_kernel", "@event_dispatcher"]
        calls:
            - [setFragmentPath, ["/_fragment"]]
        tags:
            - {name: "kernel.fragment_renderer"}
