imports:
    - { resource: config_prod.yml }

framework:
    test: ~

doctrine:
    dbal:
        host:     "localhost"

services:
    pdo:
        class: Doctrine\DBAL\Driver\PDOConnection
        arguments:
            - "mysql:host=localhost;port=3306;dbname=studysauce"
            - study
            - itekIO^#(
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION
