security:
    access_denied_url: /denied
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                username_parameter: "email"
                password_parameter: "pass"
                intention: "account_login"
                csrf_parameter: "csrf_token"
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
                failure_path: "/login"
                login_path: "/login"
                check_path: "/authenticate"
                default_target_path: /home
            logout:
                path: /logout
                target: /
            anonymous:    true
            remember_me:
                key:      "%kernel.secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                always_remember_me: true
                user_provider: fos_userbundle
            oauth:
                resource_owners:
                    facebook:           "/login/facebook"
                    google:             "/login/google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                default_target_path: /home
                oauth_user_provider:
                    service: my_user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }